Models/CrmManager/CloseDiscussionListMessage.cs
using System.Threading.Tasks;
using CdscntMkpApiReference_Prod;
using System.Xml.Serialization;

namespace cdscntapimkpwebapp1.Models.CrmManager
{
    public class CloseDiscussionListMessage:Message
    {
        public Task<CloseDiscussionResultMessage> _CloseDiscussionResultMessage;
        public CloseDiscussionListMessage(CloseDiscussionListRequest MyRequest)
        {
            _Environment = MyRequest._EnvironmentSelected;
            GetService();
            _CloseDiscussionResultMessage = _MarketplaceAPIService.CloseDiscussionListAsync(MyRequest._HeaderMessage, MyRequest._CloseDiscussionRequest);
            XmlSerializer xmlSerializer = new XmlSerializer(_CloseDiscussionResultMessage.GetType());

            _RequestXML = _RequestInterceptor.LastRequestXML;
            _MessageXML = _RequestInterceptor.LastResponseXML;
        }
    }
}

Models/CrmManager/CloseDiscussionListRequest.cs
using CdscntMkpApiReference_Prod;

namespace cdscntapimkpwebapp1.Models.CrmManager
{
    public class CloseDiscussionListRequest:Request
    {
            public CloseDiscussionRequest _CloseDiscussionRequest { get; set; }


            public CloseDiscussionListRequest()
            {
                _CloseDiscussionRequest = new CloseDiscussionRequest();
            }

        
    }
}

Models/CrmManager/GetDiscussionMailMessage.cs
using System.Threading.Tasks;
using CdscntMkpApiReference_Prod;
using System.Xml.Serialization;

namespace cdscntapimkpwebapp1.Models.CrmManager
{
    public class GetDiscussionMailMessage:Message
    {
        public Task<DiscussionMailListMessage> _DiscussionMailListMessage;
        public GetDiscussionMailMessage(GetDiscussionsMailRequest MyRequest)
        {
            _Environment = MyRequest._EnvironmentSelected;
            GetService();
            _DiscussionMailListMessage = _MarketplaceAPIService.GetDiscussionMailListAsync(MyRequest._HeaderMessage,MyRequest._GetDiscussionMailListRequest);
            XmlSerializer xmlSerializer = new XmlSerializer(_DiscussionMailListMessage.GetType());

            _RequestXML = _RequestInterceptor.LastRequestXML;
            _MessageXML = _RequestInterceptor.LastResponseXML;
        }
    }
}

Models/CrmManager/GetDiscussionMailRequest.cs
using CdscntMkpApiReference_Prod;

namespace cdscntapimkpwebapp1.Models.CrmManager
{
    public class GetDiscussionsMailRequest:Request
    {
        public GetDiscussionMailListRequest _GetDiscussionMailListRequest;


        public GetDiscussionsMailRequest()
        {
            _GetDiscussionMailListRequest = new GetDiscussionMailListRequest();
        }


    }
}

Models/CrmManager/GetOfferQuestionListMessage.cs
using System.Threading.Tasks;
using CdscntMkpApiReference_Prod;
using System.Xml.Serialization;

namespace cdscntapimkpwebapp1.Models.CrmManager
{
    public class GetOfferQuestionListMessage:Message
    {
        Task<OfferQuestionListMessage> _OfferQuestionListMessage;
       public GetOfferQuestionListMessage(GetOfferQuestionListRequest MyRequest)
        { 
            _Environment = MyRequest._EnvironmentSelected;
            GetService();
            _OfferQuestionListMessage = _MarketplaceAPIService.GetOfferQuestionListAsync(MyRequest._HeaderMessage,MyRequest._OfferQuestionFilter);
            XmlSerializer xmlSerializer = new XmlSerializer(_OfferQuestionListMessage.GetType());

            _RequestXML = _RequestInterceptor.LastRequestXML;
            _MessageXML = _RequestInterceptor.LastResponseXML;
        }
    }
}

Models/CrmManager/GetOfferQuestionListRequest.cs
using CdscntMkpApiReference_Prod;

namespace cdscntapimkpwebapp1.Models.CrmManager
{
    
    public class GetOfferQuestionListRequest:Request
    {
        public OfferQuestionFilter _OfferQuestionFilter;
        public GetOfferQuestionListRequest()
        {
            _OfferQuestionFilter = new OfferQuestionFilter();
        }
    }
}

Models/CrmManager/GetOrderClaimListMessage.cs
using CdscntMkpApiReference_Prod;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace cdscntapimkpwebapp1.Models.CrmManager
{
    public class GetOrderClaimListMessage:Message
    {
        Task<OrderClaimListMessage> _OrderClaimListMessage;
        public GetOrderClaimListMessage(GetOrderClaimListRequest MyRequest)
        {
            _Environment = MyRequest._EnvironmentSelected;
            GetService();
      //      MyRequest._OrderClaimFilter.OrderNumberList[0] = "17021521164NH3V";
            _OrderClaimListMessage = _MarketplaceAPIService.GetOrderClaimListAsync(MyRequest._HeaderMessage, MyRequest._OrderClaimFilter) ;
            XmlSerializer xmlSerializer = new XmlSerializer(_OrderClaimListMessage.GetType());

            _RequestXML = _RequestInterceptor.LastRequestXML;
            _MessageXML = _RequestInterceptor.LastResponseXML;
        }
    }
}

Models/CrmManager/GetOrderClaimListRequest.cs
using CdscntMkpApiReference_Prod;

namespace cdscntapimkpwebapp1.Models.CrmManager
{

    public class GetOrderClaimListRequest:Request
    {
        public OrderClaimFilter _OrderClaimFilter;
        public GetOrderClaimListRequest()
        {
            _OrderClaimFilter = new OrderClaimFilter();

            _OrderClaimFilter.OrderNumberList = new string[1];
            //_OrderClaimFilter.OrderNumberList[0]= "17021521164NH3V";
        }


    }
}

Controllers/CrmManagerController.cs
using Microsoft.AspNetCore.Mvc;
using cdscntapimkpwebapp1.Models;
using cdscntapimkpwebapp1.Models.CrmManager;
using Microsoft.AspNetCore.Http;
using cdscntapimkpwebapp1.Enumeration;
using System;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace cdscntapimkpwebapp1.Controllers
{
    public class CrmManagerController : Controller
    {
        // GET: /<controller>/
        const string SessionLogin = "_Login";
        const string SessionToken = "_Token";
        const string SessionEnvironment = "_Environment";


        //Autentication _Autentication;
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Welcome()
        {
            //ViewData["Message"] = "Hello " + name;
            //ViewData["NumTimes"] = numTimes;

            return View();
        }

        public void GetSessionData(ref Request MyRequest)
        {
            /*if (HttpContext.Session.GetString(SessionToken) != null)
            {
                MyRequest._Login = HttpContext.Session.GetString(SessionLogin);
                MyRequest._Token = HttpContext.Session.GetString(SessionToken);
                MyRequest._EnvironmentSelected = (EnvironmentEnum)Enum.Parse(typeof(EnvironmentEnum), HttpContext.Session.GetString(SessionEnvironment));
            }*/

        }
        public void SetSessionData(Request MyRequest)
        {
            /*if (MyRequest != null)
            {
                HttpContext.Session.SetString(SessionLogin, MyRequest._Login);
                HttpContext.Session.SetString(SessionToken, MyRequest._Autentication._Token);
                HttpContext.Session.SetString(SessionEnvironment, MyRequest._EnvironmentSelected.ToString());
            }*/
        }
        
        public ActionResult GetOrderClaimListRequest()
        {
            Request MyRequest = new GetOrderClaimListRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult GetOrderClaimListMessage(GetOrderClaimListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetOrderClaimListMessage(MyRequest));
        }
        public ActionResult GetOfferQuestionListRequest()
        {
            Request MyRequest = new GetOrderClaimListRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult GetOfferQuestionListMessage(GetOfferQuestionListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetOfferQuestionListMessage(MyRequest));
        }
        public ActionResult CloseDiscussionListRequest()
        {
            Request MyRequest = new CloseDiscussionListRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult CloseDiscussionListMessage(CloseDiscussionListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new CloseDiscussionListMessage(MyRequest));
        }

        public ActionResult GetDiscussionMailListRequest()
        {
            Request MyRequest = new GetDiscussionsMailRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult GetDiscussionMailListMessage(GetDiscussionsMailRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetDiscussionMailMessage(MyRequest));
        }
    }
}

Views/CrmManager/CloseDiscussionListMessage.cshtml
@model cdscntapimkpwebapp1.Models.CrmManager.CloseDiscussionListMessage

@{
    ViewData["Title"] = "CloseDiscussionList";
}

<br />
<br />
<div>
    <h4>CloseDiscussionList</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Parameters
        </dt>
        <dd>
            @Html.DisplayNameFor(model => model._Token) :
            @Html.DisplayFor(model => model._Token)
        </dd>
        <dt>
            Request
        </dt>
        <dd>
            <pre> @Html.DisplayFor(model => model._RequestXML)</pre>
        </dd>
        <dt>
            Response
        </dt>
        <dd>
            <pre> @Html.DisplayFor(model => model._MessageXML)</pre>
        </dd>
    </dl>
</div>

Views/CrmManager/CloseDiscussionListRequest.cshtml
@using cdscntapimkpwebapp1.Enumeration
@using CdscntMkpApiReference_Prod;


@model cdscntapimkpwebapp1.Models.CrmManager.CloseDiscussionListRequest


@{
    ViewData["Title"] = "Index";
}


@using (Html.BeginForm("CloseDiscussionListMessage", "CrmManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <br />
    <br />
    <h2>GetProductListByIdentifier</h2>
    <div class="col-xs-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Identification</h3>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                    <br />
                    <div role="tabpanel" class="tab-pane active" id="loginTab">
                        <div class="form-group">
                            <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
                            @Html.TextBoxFor(model => model._Login, new { @id = "login", @class = "form-control", @placeholder = "Login" })
                        </div>
                        <div class="form-group">
                            <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
                            @Html.TextBoxFor(model => model._Password, new { @id = "password", @class = "form-control", @placeholder = "Password", @type = "password" })
                        </div>
                        <div class="form-group">
                            <label for="token"><span class="glyphicon glyphicon-qrcode"></span> Token</label>
                            @Html.TextBoxFor(model => model._Token, new { @id = "token", @class = "form-control", @placeholder = "Token" })
                        </div>
                        <div class="form-group">
                            <label for="token"><span class="glyphicon glyphicon-qrcode"></span> Environment</label>
                            <br />
                            <p class="nav navbar-nav navbar-left">
                                @Html.DropDownListFor(m => m._EnvironmentSelected, new SelectList(Enum.GetValues(typeof(EnvironmentEnum))),
                    "Select Environment")
                            </p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Parameters</h3>
        </div>
        <div class="panel-body">

            <label for="OfferPoolId"><span class="glyphicon glyphicon-comment"></span> OfferPoolId</label>
            @Html.TextBoxFor(model => model._CloseDiscussionRequest.DiscussionIds, new { @id = "poolId", @class = "form-control", @placeholder = "poolId" })          

        </div>
    </div>


    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-info" />
        <input type="reset" value="Reset" class="btn btn-default" />
    </div>
                                    }

Views/CrmManager/GetDiscussionMailListMessage.cshtml
@model cdscntapimkpwebapp1.Models.CrmManager.CloseDiscussionListMessage

@{
    ViewData["Title"] = "CloseDiscussionList";
}

<br />
<br />
<div>
    <h4>CloseDiscussionList</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            Parameters
        </dt>
        <dd>
            @Html.DisplayNameFor(model => model._Token) :
            @Html.DisplayFor(model => model._Token)
        </dd>
        <dt>
            Request
        </dt>
        <dd>
            <pre> @Html.DisplayFor(model => model._RequestXML)</pre>
        </dd>
        <dt>
            Response
        </dt>
        <dd>
            <pre> @Html.DisplayFor(model => model._MessageXML)</pre>
        </dd>
    </dl>
</div>

Views/CrmManager/GetDiscussionMailListRequest.cshtml
@using cdscntapimkpwebapp1.Enumeration
@using CdscntMkpApiReference_Prod;


@model cdscntapimkpwebapp1.Models.CrmManager.GetDiscussionsMailRequest


@{
    ViewData["Title"] = "Index";
}


@using (Html.BeginForm("GetDiscussionsMailMessage", "CrmManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <br />
    <br />
    <h2>GetDiscussionMailList</h2>
    <div class="col-xs-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Identification</h3>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                    <br />
                    <div role="tabpanel" class="tab-pane active" id="loginTab">
                        <div class="form-group">
                            <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
                            @Html.TextBoxFor(model => model._Login, new { @id = "login", @class = "form-control", @placeholder = "Login" })
                        </div>
                        <div class="form-group">
                            <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
                            @Html.TextBoxFor(model => model._Password, new { @id = "password", @class = "form-control", @placeholder = "Password", @type = "password" })
                        </div>
                        <div class="form-group">
                            <label for="token"><span class="glyphicon glyphicon-qrcode"></span> Token</label>
                            @Html.TextBoxFor(model => model._Token, new { @id = "token", @class = "form-control", @placeholder = "Token" })
                        </div>
                        <div class="form-group">
                            <label for="token"><span class="glyphicon glyphicon-qrcode"></span> Environment</label>
                            <br />
                            <p class="nav navbar-nav navbar-left">
                                @Html.DropDownListFor(m => m._EnvironmentSelected, new SelectList(Enum.GetValues(typeof(EnvironmentEnum))),
                    "Select Environment")
                            </p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Parameters</h3>
        </div>
        <div class="panel-body">

            <label for="DiscussionIds"><span class="glyphicon glyphicon-comment"></span> DiscussionIds</label>
            @Html.TextBoxFor(model => model._GetDiscussionMailListRequest.DiscussionIds, new { @id = "DiscussionIds", @class = "form-control", @placeholder = "DiscussionIds" })

        </div>
    </div>


    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-info" />
        <input type="reset" value="Reset" class="btn btn-default" />
    </div>
}

Views/CrmManager/GetOfferQuestionListMessage.cshtml
@model cdscntapimkpwebapp1.Models.CrmManager.GetOfferQuestionListMessage

@{
    ViewData["Title"] = "GetOfferQuestionList";
}

<br />
<br />
<div>
    <h4>GetOfferQuestionList</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Parameters
        </dt>
        <dd>
            @Html.DisplayNameFor(model => model._Token) :
            @Html.DisplayFor(model => model._Token)
        </dd>
        <dt>
            Request
        </dt>
        <dd>
            <pre> @Html.DisplayFor(model => model._RequestXML)</pre>
        </dd>
        <dt>
            Response
        </dt>
        <dd>
            <pre> @Html.DisplayFor(model => model._MessageXML)</pre>
        </dd>
    </dl>
</div>

Views/CrmManager/GetOfferQuestionListRequest.cshtml
@using cdscntapimkpwebapp1.Enumeration
@using CdscntMkpApiReference_Prod;


@model cdscntapimkpwebapp1.Models.CrmManager.GetOfferQuestionListRequest


@{
    ViewData["Title"] = "Index";
}


@using (Html.BeginForm("GetOfferQuestionListMesage", "CrmManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <br />
    <br />
    <h2>GetOfferQuestionList</h2>
    <div class="col-xs-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Identification</h3>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                    <br />
                    <div role="tabpanel" class="tab-pane active" id="loginTab">
                        <div class="form-group">
                            <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
                            @Html.TextBoxFor(model => model._Login, new { @id = "login", @class = "form-control", @placeholder = "Login" })
                        </div>
                        <div class="form-group">
                            <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
                            @Html.TextBoxFor(model => model._Password, new { @id = "password", @class = "form-control", @placeholder = "Password", @type = "password" })
                        </div>
                        <div class="form-group">
                            <label for="token"><span class="glyphicon glyphicon-qrcode"></span> Token</label>
                            @Html.TextBoxFor(model => model._Token, new { @id = "token", @class = "form-control", @placeholder = "Token" })
                        </div>
                        <div class="form-group">
                            <label for="token"><span class="glyphicon glyphicon-qrcode"></span> Environment</label>
                            <br />
                            <p class="nav navbar-nav navbar-left">
                                @Html.DropDownListFor(m => m._EnvironmentSelected, new SelectList(Enum.GetValues(typeof(EnvironmentEnum))),
                    "Select Environment")
                            </p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Parameters</h3>
        </div>
        <div class="panel-body">

            <label for="Select Filter Criterion">Select OrderState</label><br />
            @Html.ListBoxFor(m => m._OfferQuestionFilter.StatusList, new SelectList(Enum.GetValues(typeof(DiscussionStateFilter))), "Select Filter Criterion")<br />
            <label for="Set BeginCreationDate"><span class="glyphicon glyphicon-calendar"></span>Set BeginCreationDate</label>
            @Html.TextBoxFor(m => m._OfferQuestionFilter.BeginCreationDate, new { @class = "form-control datepicker", placeholder = "Select BeginCreationDate" })<br />
            <label for="Set BeginModificationDate"><span class="glyphicon glyphicon-calendar"></span>Set BeginModificationDate</label>
            @Html.TextBoxFor(m => m._OfferQuestionFilter.BeginModificationDate, new { @class = "form-control datepicker", placeholder = "Select BeginModificationDate" })<br />
            <label for="Set EndCreationDate"><span class="glyphicon glyphicon-calendar"></span>Set EndCreationDate</label>
            @Html.TextBoxFor(m => m._OfferQuestionFilter.EndCreationDate, new { @class = "form-control datepicker", placeholder = "Select EndCreationDate" })<br />
            <label for="Set EndModificationDate"><span class="glyphicon glyphicon-calendar"></span>Set EndModificationDate</label>
            @Html.TextBoxFor(m => m._OfferQuestionFilter.EndModificationDate, new { @class = "form-control datepicker", placeholder = "Select EndModificationDate" })<br />
            <label for="Select Corporation Code"><span class="glyphicon glyphicon-copyright-mark"></span>Select Corporation Code</label>
            @Html.TextBoxFor(m => m._OfferQuestionFilter.ProductEANList, new { @id = "CorporationCode", @class = "form-control", @placeholder = "parameter" })<br />
            <label for="Select Corporation Code"><span class="glyphicon glyphicon-copyright-mark"></span>Select Corporation Code</label>
            @Html.TextBoxFor(m => m._OfferQuestionFilter.ProductEANList, new { @id = "CorporationCode", @class = "form-control", @placeholder = "parameter" })<br />
                       

        </div>
    </div>


    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-info" />
        <input type="reset" value="Reset" class="btn btn-default" />
    </div>
}

Views/CrmManager/GetOrderClaimListMessage.cshtml
@model cdscntapimkpwebapp1.Models.CrmManager.GetOrderClaimListMessage

@{
    ViewData["Title"] = "GetOrderClaimList";
}

<br />
<br />
<div>
    <h4>GetOrderClaimList</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Parameters
        </dt>
        <dd>
            @Html.DisplayNameFor(model => model._Token) :
            @Html.DisplayFor(model => model._Token)
        </dd>
        <dt>
            Request
        </dt>
        <dd>
            <pre> @Html.DisplayFor(model => model._RequestXML)</pre>
        </dd>
        <dt>
            Response
        </dt>
        <dd>
            <pre> @Html.DisplayFor(model => model._MessageXML)</pre>
        </dd>
    </dl>
</div>

Views/CrmManager/GetOrderClaimListRequest.cshtml
@using cdscntapimkpwebapp1.Enumeration
@using CdscntMkpApiReference_Prod;


@model cdscntapimkpwebapp1.Models.CrmManager.GetOrderClaimListRequest


@{
    ViewData["Title"] = "Index";
}


@using (Html.BeginForm("GetOrderClaimListMessage", "CrmManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <br />
    <br />
    <h2>GetOfferQuestionList</h2>
    <div class="col-xs-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Identification</h3>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                    <br />
                    <div role="tabpanel" class="tab-pane active" id="loginTab">
                        <div class="form-group">
                            <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
                            @Html.TextBoxFor(model => model._Login, new { @id = "login", @class = "form-control", @placeholder = "Login" })
                        </div>
                        <div class="form-group">
                            <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
                            @Html.TextBoxFor(model => model._Password, new { @id = "password", @class = "form-control", @placeholder = "Password", @type = "password" })
                        </div>
                        <div class="form-group">
                            <label for="token"><span class="glyphicon glyphicon-qrcode"></span> Token</label>
                            @Html.TextBoxFor(model => model._Token, new { @id = "token", @class = "form-control", @placeholder = "Token" })
                        </div>
                        <div class="form-group">
                            <label for="token"><span class="glyphicon glyphicon-qrcode"></span> Environment</label>
                            <br />
                            <p class="nav navbar-nav navbar-left">
                                @Html.DropDownListFor(m => m._EnvironmentSelected, new SelectList(Enum.GetValues(typeof(EnvironmentEnum))),
                    "Select Environment")
                            </p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">Parameters</h3>
        </div>
        <div class="panel-body">

            <label for="Select Filter Criterion">Select discussion Status </label><br />
            @Html.ListBoxFor(m => m._OrderClaimFilter.StatusList, new SelectList(Enum.GetValues(typeof(DiscussionStateFilter))), "Select Filter Criterion")<br />
            <label for="Set BeginCreationDate"><span class="glyphicon glyphicon-calendar"></span>Set BeginCreationDate</label>
            @Html.TextBoxFor(m => m._OrderClaimFilter.BeginCreationDate, new { @class = "form-control datepicker", placeholder = "Select BeginCreationDate" })<br />
            <label for="Set BeginModificationDate"><span class="glyphicon glyphicon-calendar"></span>Set BeginModificationDate</label>
            @Html.TextBoxFor(m => m._OrderClaimFilter.BeginModificationDate, new { @class = "form-control datepicker", placeholder = "Select BeginModificationDate" })<br />
            <label for="Set EndCreationDate"><span class="glyphicon glyphicon-calendar"></span>Set EndCreationDate</label>
            @Html.TextBoxFor(m => m._OrderClaimFilter.EndCreationDate, new { @class = "form-control datepicker", placeholder = "Select EndCreationDate" })<br />
            <label for="Set EndModificationDate"><span class="glyphicon glyphicon-calendar"></span>Set EndModificationDate</label>
            @Html.TextBoxFor(m => m._OrderClaimFilter.EndModificationDate, new { @class = "form-control datepicker", placeholder = "Select EndModificationDate" })<br />
            <label for="Select OrderNumber"><span class="glyphicon glyphicon-copyright-mark"></span>Select OrderNumber</label>
            @Html.TextBoxFor(m => m._OrderClaimFilter.OrderNumberList[0], new { @id = "OrderNumberList", @class = "form-control", @placeholder = "parameter" })<br />
        

        </div>
    </div>


    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-info" />
        <input type="reset" value="Reset" class="btn btn-default" />
    </div>
}